name: Jenkins build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:  "http://localhost:8080/" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
          jenkins-job: "ThunderdomeTestBuild" # The name of the jenkins job to run
          jenkins-username: "harishtanu" # user name for accessing jenkins
          jenkins-pat: "" # personal Access token for accessing Jenkins
          poll-time: 10 # how often (seconds) to poll the jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging

