name: Jenkins build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout:
   uses: ThunderdomeTest/.github/workflows/jenkins_build.yml@main
   with:
    jdk_version: 11
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: actions/checkout@v2
      with:
        url: "http://localhost:8080"
        job: "ThunderdomeTestBuild"

