name: Jenkins Build

on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: harishtanu007/ThunderdomeTest@main
      with:
        url: "http://localhost:8080"
        job: "ThunderdomeTestBuild"

